-- Create an initial admin user.
--
-- Usage:
--   Run this AFTER loading schema.sql.
--   psql -U postgres -h localhost -d ppm -f seed-admin.sql
--
-- The password hash below is a bcrypt $2b$ hash generated by Node.js.
-- The app uses Node's `bcrypt` package to verify passwords at login,
-- which produces/expects $2b$ hashes. PostgreSQL's pgcrypto extension
-- generates $2a$ hashes instead, which can cause verification to fail.
-- That's why we use a pre-computed hash rather than crypt() + gen_salt().
--
-- To change the password, generate a new hash with:
--   node -e "require('bcrypt').hash('YOUR_NEW_PASSWORD',12).then(h=>console.log(h))"
-- Then replace the hash string below.

INSERT INTO public.actor (first_name, last_name, email, password_hash, system_role)
VALUES (
  'Admin',
  'User',
  'admin@ppm.local',
  '$2b$12$Apefv62FXjRniKKj3ndq9ecwMwnFVEQI4QDmG72FhQV18XxsAlvYa',
  'ADMIN'
);
